# Dieses Repo ist Teil des Heimgewebes.
# Systemweiter Kontext durch Heimgeist:
#   metarepo/ai-contexts/heimgeist.ai-context.yml

system_context:
  heimgeist: "../metarepo/ai-contexts/heimgeist.ai-context.yml"

ai_context_version: 1.0

project:
  name: heimlern
  summary: Reinforcement-/Bandit-Policy-Framework (Rust)
  role: policy_engine
  primary_language: rust
  visibility: internal

dependencies:
  internal:
    - name: chronik
      relationship: uses
      interface:
        - event_feed
        - metrics
    - name: contracts
      relationship: uses
      interface:
        - json_schema
  external:
    - name: pydantic
    - name: pandas

architecture:
  entrypoints:
    - crates/heimlern-bandits/examples/decide.rs
    - crates/heimlern-bandits/src/lib.rs
  key_paths:
    - path: src/scoring/
      purpose: quality scoring & policy checks
  data_flow:
    input: events/metrics from chronik
    processing: scoring + feedback
    output: reports/signals

conventions:
  branching: "main, feature/*"
  commit_prefix: "heimlern"
  ci_platform: github_actions

documentation:
  adr: docs/adr/
  runbook: docs/runbook.md

ai_guidance:
  do:
    - log model versions and seeds for reproducibility
  dont:
    - change scoring semantics without a version bump
