name: 'Check for @main or @master references in Actions'
description: 'Checks for @main or @master references in GitHub Actions workflow files.'
runs:
  using: 'composite'
  steps:
    - name: Check for default branch references
      run: |
        if grep -rE "uses:.*@(main|master)([[:space:]]|$)" .github/workflows/; then
          echo "Error: Found '@main' or '@master' references in workflow files. Please use a specific commit SHA or tag."
          exit 1
        fi
      shell: bash
