name: contracts
permissions:
  contents: read
on:
  push:
  pull_request:
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements-tools.txt
      - name: Generate examples
        run: python scripts/examples.py
      - name: Validate snapshot
        run: python scripts/validate_json.py contracts/policy_snapshot.schema.json /tmp/heimlern_snapshot.json
      - name: Validate feedback
        run: python scripts/validate_json.py contracts/policy_feedback.schema.json /tmp/heimlern_feedback.json
