name: validate (aussen in heimlern)
permissions:
  contents: read
on: [push, pull_request, workflow_dispatch]
jobs:
  samples:
    name: samples (data/samples/aussensensor.jsonl)
    if: ${{ hashFiles('data/samples/aussensensor.jsonl') != '' }}
    uses: heimgewebe/metarepo/.github/workflows/reusable-validate-jsonl.yml@contracts-v1
    with:
      jsonl_path: data/samples/aussensensor.jsonl
      schema_url: https://raw.githubusercontent.com/heimgewebe/metarepo/contracts-v1/contracts/aussen.event.schema.json
      strict: false
      validate_formats: true

  fixtures:
    name: fixtures (tests/fixtures/aussen.jsonl)
    if: ${{ hashFiles('tests/fixtures/aussen.jsonl') != '' }}
    uses: heimgewebe/metarepo/.github/workflows/reusable-validate-jsonl.yml@contracts-v1
    with:
      jsonl_path: tests/fixtures/aussen.jsonl
      schema_url: https://raw.githubusercontent.com/heimgewebe/metarepo/contracts-v1/contracts/aussen.event.schema.json
      strict: false
      validate_formats: true
